### ISSUE TITLE
JSON Strings vs Objects

### ISSUE THREAD

**Issue by airmrcr** [scryptmouse/Backbone.ChromeStorage#5]
Why are models are being stringified when they are sync'd? Since `chrome.storage.*` supports objects I was wondering if there was any reason this was done or was it just carried over from `Backbone.LocalStorage`? It's not really important but if it's not required it might be best to remove it to avoid performance hits.

**Comment by scryptmouse** [comment]
It was something carried over from Backbone.LocalStorage, yep. I am hoping to have some time this weekend to work on this project and that is something on the to-do list.

**Comment by airmrcr** [comment]
I thought so. I'm looking forward to your changes as I want to use your library in my extensions but don't like the idea of storing strings in the long run and updating data in `chrome.storage.*` can be tricky.

Also, I was wondering you decided to use `$.Deferred` instead of Backbone's own async handling (e.g. `success` and `error` callbacks in `options` parameters? Although I do like it, I feel like it changes the async pattern many Backbone devs are used to. Perhaps if a dev wants async code handled this way they could _also_ use another Backbone extension? This is only my opinion of course :)

**Comment by nigel-gott** [comment]
Also internally I am not sure we even need a records array combined with storing the records string in local storage.

The only place I can see where it is actually used is in findAll to get every model in the collection. But I think if the internal storage layout is changed to using objects we could instead just get the collection object which itself will contain all of the models in that collection. 

Removing records entirely would simplify the code and remove the need for having to update the records string for concurrency between pages.

Unless I am missing a legit use for it somewhere else!

**Comment by airmrcr** [comment]
@nigggle That sounds good, but for big collections this means that we'd always be fetching/syncing **all** models from `chrome.storage.*` at any one time. We couldn't just update a single model in a collection because it's stored in the collection.

As much as I like your suggestion and the pattern it supports, I just don't think that the `chrome.storage.*` API is good enough at this point. Correct me if I'm wrong though.

My main concern is storing Objects as Strings and the use of `$.Deferred`. To clarify on the latter, the author of Backbone is already investigating adding support for Futures/Promises to the core, so I personally think this plugin should concentrate solely on interacting with `chrome.storage.*` and let developers choose how they handle async coding. I'd probably still use something like `$.Deferred`, but my point is that I don't think it belongs here. Just my two cents.

I love the library btw! It saved me a lot of time creating one :)

**Comment by nigel-gott** [comment]
@neocotic Ah yes I see now, I was under the incorrect impression we could modify / get individual sub objects using chrome.set/get.

**Comment by scryptmouse** [comment]
I didn't have as much time this weekend as I'd hoped, but stringification is gone.

Retrieving from chrome.storage should call `JSON.parse` / `.split(',')` to migrate from older data, but will now use plain arrays / objects whenever it saves.

Hopefully I can look at using Backbone's success / error callbacks vs $.Deferred later this week. And I am happy to see someone finding this useful!

**Comment by airmrcr** [comment]
I've only had a look at your commits so far but it looks great and well done for tackling the backwards compatability issue so gracefully. I'm could understand if you didn't want to replace `$.Deffered` with Backbone's async pattern as it is nicer and remain compatible without current implementations, but I also think that it'd be more beneficial to have the same pattern as core Backbone so it'd be easier to upgrade core as well as use other plugins. Again, only make these changes if you agree as they are only my opinions and would be open for debate. 

I'll look at adding these changes to my alpha project this week and will try to test edge cases.

**Comment by airmrcr** [comment]
Ignore what I said about `$.Deferred`. I realise now that your code actually mimics Backbone's sync pattern really well. I wasn't aware that Backbone already returns a jqXHR object in these cases which already implements `$.Deferred` and I see now that you're also supporting the callback options.

Basically, leave your sync handling as it is. You've done a great job.

Also, since I'm more than happy with the object storage now I'm going to close this issue off.
