### ISSUE TITLE
bindAll must be passed function names

### ISSUE THREAD

**Issue by tomasvanrijsse** [scryptmouse/Backbone.ChromeStorage#8]
Chrome gives me an error saying:
"Uncaught Error: bindAll must be passed function names"

In the constructor on line 110 you write "_.bindAll(this);"

According to the underscore docs on http://underscorejs.org/#bindAll it demands that the second parameter should be a methodName.
I can't figure what you meant to do but it isn't working anymore.

**Comment by scryptmouse** [comment]
_.bindAll used to do what the name says if you didn't pass any functions, in versions <= 1.5 or so. Unfortunately underscore forgot about semantic versioning and broke that functionality in a minor release.

I've just pushed a fix. Thank you for the report!
